### ISSUE TITLE
Add nixpkgs-fmt to buildInputs

### ISSUE THREAD

**Issue by cyntheticfox** [yusdacra/rust-nix-templater#11]
Your application depends on `nixpkgs-fmt` to format the flake.nix file, and while you include it in the `devShell.nix` you don't in the `buildInputs` or in the `propagatedBuildInputs` which would allow you to define it as a runtime dependency.

You should also disclose that it does run that in the `README.md`.

It is also a slight security concern to simply call 'nixpkgs-fmt' from the PATH environment variable; you could substitute it by placing your own `nixpkgs-fmt` binary that does whatever in that directory. It's not like this would be a `setuid` binary, but its still something to consider.

**Comment by 90-008** [comment]
I was thinking of providing `nixpkgs-fmt` through the `nix` available on the system (would also be used for #5, to provide cargo). A naive implementation would be using `nix-shell`, but that still has the security concerns. Honestly I don't think it's a big issue, but if we can go around that somehow by using a library or something to communicate with `nix` (or the nix daemon?) it would be better.

**Comment by cyntheticfox** [comment]
Flakes are supposed to be hermetic (self-sealed), so it'd probably be best to keep `nixpkgs-fmt` as a `buildInput`. That way, your application is guaranteed to work, since it's purely calling its given inputs, and doesn't depend on outside state. For the flake that is generated, you could provide `nixpkgs-fmt` as a `devShell` dependency to maintain formatting of the flake.

Is there a particular reason you want to try to use the system's binaries instead of nixpkgs or better yet, dependencies?

**Comment by 90-008** [comment]
Hmm, I was thinking of how to use them in code from `buildInputs` but I think I found the best way to do it. So basically we would provide `nixpkgs-fmt` and `cargo` in the build derivation through `buildInputs`, and set `FMT_BIN` and `CARGO_BIN` to their respective binaries. By using a `build.rs` file, we can read these environment variables at compile time, and use them in our code. This will ensure that correct binaries get used. While developing `rust-nix-templater` itself, it will just default to `nixpkgs-fmt` and `cargo` respectively, to avoid breakage.

Also generated devShell already contains `nixpkgs-fmt` so no problems there.

**Comment by cyntheticfox** [comment]
That sounds like a working solution, yeah. It would allow you to set the binaries to the input versions, while still allowing a path locally for developing.
