### ISSUE TITLE
 Cargo.toml as nix configuration source

### ISSUE THREAD

**Issue by kkharji** [yusdacra/rust-nix-templater#13]
Hey @yusdacra, 

Truly very useful project, I'm getting started with creating a rust dev env, and I was almost done with the intention of creating a github template for future project until I stumbled upon this awesome project.

If I may, I believe things like package name, package version should be dynamically linked to Cargo.toml. That simplifies a lot of things.

For example:
`mainToml = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).package;
 mainName =  mainToml.name`

then package/project name can be accessed by `mainName`. 

Additionally it would be nice if the package version defined be add to naersk buildPacakge function.

What do you think? 

Thanks

**Comment by 90-008** [comment]
`naersk` already does this while building the package (it uses the crate name and version from `Cargo.toml`). But I agree with the idea. We could read `Cargo.toml` before starting to generate anything and check if fields like `name`, `description`, `license` etc. exist, and if they do we can just skip getting those from the user, and instead directly use the ones in `Cargo.toml`. Other behaviour will stay the same. This would also reduce what a user needs to pass to `rust-nix-templater`.

**Comment by kkharji** [comment]
Yah and if the project is already in place, otherwise when the user decide to change the version or the name of the project, he can do it from `Cargo.toml` and not touch `flake.nix` which decrease the overhead of maintaining nix part when introducing such changes.

**Comment by kkharji** [comment]
Extending this idea a bit further, (aside from name/version/desc take from package section in `Cargo.toml`) and create a new section in `Cargo.toml` called `nix` for stuff like `neededLibs`, `buildInputs`, `nativeBuildInputs`, `env`. 

Then in nix files we just concat lists from Cargo.toml, for example buildInput, with the empty buildInput in common, that way user can still use common.nix only or mismatch them when it makes sense (e.g. use nix for overlays only)
