### ISSUE TITLE
Cargo.lock: no such file

### ISSUE THREAD

**Issue by kkharji** [yusdacra/rust-nix-templater#14]
Trying to run `nix build/run` on newly generated file result in this error, wouldn't it be nice if this is taken care by nix? I can't think of a solution right now

**Comment by 90-008** [comment]
I believe we can workaround this by running an initial `cargo build`. `Cargo.lock` has to be committed to the VCS for `naersk` to work, so we can also add a warning / note for that.

**Comment by kkharji** [comment]
Yep a warring would be sufficient to manage user expectations.  For this bug maybe [`cargo generate-lockfile`](https://doc.rust-lang.org/cargo/commands/cargo-generate-lockfile.html) be what we need to run after generating the project.

**Comment by 90-008** [comment]
> For this bug maybe cargo generate-lockfile be what we need to run after generating the project.

Ah right, I forgot about that command. We should use that indeed.

**Comment by kkharji** [comment]
Awesome work @yusdacra , thank you.
