### ISSUE TITLE
feat: generate a devshell toml and use it with nix file

### ISSUE THREAD

**Issue by 90-008** [yusdacra/rust-nix-templater#16]

**Comment by 90-008** [comment]
I think the way I want to do this is that we have a `package.metadata.nix.devshell` key. This key can either point to a file, or it can be an attribute set. If it points to a file we use the file, if it's an attribute set we use the attribute set for devshell config. This way the user can choose whether they want the configuration to stay in one place (`Cargo.toml`) or if they already have a seperate devshell config file they can use that.

**Comment by 90-008** [comment]
https://github.com/yusdacra/rust-nix-templater/commit/926edde1a5dca4c4495aac9091328f89fe3a6488 implements this, but without being able to specify a file to use. Currently it checks if `devshell.toml` exists and uses that, otherwise tries to use the `devshell` attr in `Cargo.toml`.

**Comment by kkharji** [comment]
:heart_eyes: I need to catch up with these amazing work.
edit: watching the repo :heart:
