### ISSUE TITLE
test failed: tests::with_executable

### ISSUE THREAD

**Issue by kkharji** [yusdacra/rust-nix-templater#18]
Hey @yusdacra, while trying to update rust-nix-templater using nix flakes. I got the following error:

```rs
rust-nix-templater> test tests::with_desktop_file ... ok
rust-nix-templater> failures:
rust-nix-templater> ---- tests::with_executable stdout ----
rust-nix-templater> - No Cargo project detected.
rust-nix-templater> 💾 Writing files...
rust-nix-templater>   - Formatting files...
rust-nix-templater>   - Failed to format: error while running `nixpkgs-fmt`: No such file or dire`
rust-nix-templater>   - Creating new Cargo project...
rust-nix-templater>   - Created Cargo project successfully: used `cargo`
rust-nix-templater>     - Generated Cargo lockfile successfully
rust-nix-templater> thread 'tests::with_executable' panicked at 'no package field in cargo toml, maybe workspace?', src/main.rs:148:10
```

**Comment by 90-008** [comment]
I think this is because we don't clean test directory before doing another test. It works with some builds and doesn't in some which I assume is related to test run order.

**Comment by kkharji** [comment]
Yah I had additional failing tests, but now and oddly after running it multiple times it build okay

**Comment by 90-008** [comment]
> Yah I had additional failing tests, but now and oddly after running it multiple times it build okay

Mhm, and additionally multiple tests may be ran at the same time, which is most likely the cause of the indeterministic behavior.

**Comment by kkharji** [comment]
> the indeterministic behavior

Like b/c of nix ?

**Comment by 90-008** [comment]
> > the indeterministic behavior
> 
> Like b/c of nix ?

Because of multithreading. Multiple tests run in parallel and write to the same location, which may cause issues.

**Comment by kkharji** [comment]
Oh I see, disable or ignore tests that maybe causing issues?

In my upcoming journal manager cli tool, I had to ignore multiple tests so that the ci won't fail

**Comment by 90-008** [comment]
https://github.com/yusdacra/rust-nix-templater/commit/c573fea89d88bfdaca14f37d59a8d336c479b8ef should've fixed it.
