### ISSUE TITLE
Help migrating 

### ISSUE THREAD

**Issue by kkharji** [yusdacra/rust-nix-templater#20]
Hey @yusdacra,

I'm having troubles find my way around the new setup the new setup. there are few things I miss from new generations.

- The ability to customize packages and builds, I miss al the guiding comments and initial template. 
  ```rust
            packages = {
            # Compiles slower but has tests and faster executable
            "app" = import ./nix/build.nix {
              inherit common;
              doCheck = true;
              release = true;
            };
            # Compiles faster but no tests and slower executable
            "app-debug" = import ./nix/build.nix { inherit common; };
          };
          checks = {
            # Compiles faster but has tests and slower executable
            "app-tests" = import ./nix/build.nix { inherit common; doCheck = true; };
          };
          apps = builtins.mapAttrs (n: v: mkApp { name = n; drv = v; exePath = "/bin/app"; }) packages;

        in
          {

            inherit packages checks apps;
            # Release build is the default package
            defaultPackage = packages."app";

            # Release build is the default app
            defaultApp = apps."app";

            devShell = import ./nix/devShell.nix { inherit common; };
          }
    );
  ```

- In the old version I had a file generate called nix where I defined buildInputs, nativeBuildInputs, env .. etc as well as a place to register overlays and use them. Is it now all moved to Cargo.yml, and if so, hmmmm how to add overlays.
- `nix build`, `nix flake check`, ... don't work as it used to.

I ran `rust-nix-templater -T -l mit -n project-name` on `v0.2.0`

Thanks

**Comment by 90-008** [comment]
First of all you should use version `v0.2.1` as it includes a fix.

Second, almost all of the Nix code is moved to https://github.com/yusdacra/nix-cargo-integration. You can provide overrides using the `overrides` attribute as mentioned in the README. I haven't yet explained how exactly the attribute works and takes but I will get around to that. I can help you if you tell me exactly what do you want (and the project's Nix code if possible). For examples, you can look at https://gitlab.com/veloren/veloren/-/blob/cca5e411a1e26ba24f1def44de297e879e115a7a/flake.nix#L19 as an example on how the `overrides` attribute works.

**Comment by kkharji** [comment]
Hmmm, Okay .. yah for the project I'm going to send an invite right now. 

For what I want, I guess a template where I can add stuff to and not having to write the overrides parts each time I generate a new project. It's a big jump from a template to library with functions for me, while a library is an excellent decision to separate concerns and ensure stability, a template is more like fill out the blank kinda style with sensible defaults that almost apply to all projects.

One of the things I loved about the old template is those helpful and reminder comments, and the organization of files in the nix dir to control project aspects, deps, builds, devshell .. etc.

Thanks for the example, do you happens to have an example for `devshell.toml` I tried to get this to work but failed:

```rust
commands: [
  {name: renv, command: "direnv reload"}
]

```

**Comment by kkharji** [comment]
Additionally, I really liked the pre-made flake commands

**Comment by 90-008** [comment]
> Thanks for the example, do you happens to have an example for `devshell.toml` I tried to get this to work but failed:
> 
> ```rust
> commands: [
>   {name: renv, command: "direnv reload"}
> ]
> ```

You can do (in `devshell.toml`):
```toml
[devshell]
name = "project-name"

[[commands]]
name = "renv"
command = "direnv reload"
```

The `devshell.toml` accepts the same attributes as https://github.com/numtide/devshell does since it uses it, so you can read their documentation.

> For what I want, I guess a template where I can add stuff to and not having to write the overrides parts each time I generate a new project. It's a big jump from a template to library with functions for me, while a library is an excellent decision to separate concerns and ensure stability, a template is more like fill out the blank kinda style with sensible defaults that almost apply to all projects.

I'm not sure what you mean by "template". `nix-cargo-integration` tries to set sensible defaults. There are documentation about which attributes can be used in `Cargo.toml`. I believe the issue is a lack of examples?

> Additionally, I really liked the pre-made flake commands

Not sure about "pre-made flake commands"?

**Comment by kkharji** [comment]
> ```yaml
> commands: [
>   {name: renv, command: "direnv reload"}
> ]
> ```

:rofl: I was writing in  yaml sorry about that 

> ```toml
> [devshell]
> name = "project-name"
> 
> [[commands]]
> name = "renv"
> command = "direnv reload"
> ```


> The `devshell.toml` accepts the same attributes as https://github.com/numtide/devshell does since it uses it, so you can read their documentation.

Hmm I will set it programmatically since this didn't work and nix is way better in this regards (function to generate the sturct name, command ... etc
 

> I'm not sure what you mean by "template". `nix-cargo-integration` tries to set sensible defaults. There are documentation about which attributes can be used in `Cargo.toml`. I believe the issue is a lack of examples?

Yes and no, no because template suppose to perform the function of guiding you to set options based on some type of organization. and yes examples would help but nothing beats 

```
-> Create new project with `rust-nix-templater` 
      -> Edit options, follow comments, and add what 
           you need/remove what you don't.
           -> Start developing.
```

Now the process might look like
```
-> Create new project with `rust-nix-templater` 
   -> Catch up and refresh your memory on `nix-cargo-integration`. 
       (open browser)
   -> Write override section and try to remember what you need 
        to override, maybe open previous generated file to reproduce.
      -> Start developing and hope you wouldn't need to modify nix stuff for 
          at least few days.
```

Does it make sense what I'm trying to say?

I think perhaps the issue, is that the template override defaults instead of supplying it. I think it would make more sense if `nix-cargo-integration` would act as a single function that accept an aggregated set of configuration (which are now defaults) as well as a library when the user want extra configuration.

> Not sure about "pre-made flake commands"?

like `nix build` to build the project to `/result/bin/` and `nix flake check` to run tests and so on.

**Comment by 90-008** [comment]
> like nix build to build the project to /result/bin/ and nix flake check to run tests and so on.

You can still do these.

> I think perhaps the issue, is that the template override defaults instead of supplying it. I think it would make more sense if nix-cargo-integration would act as a single function that accept an aggregated set of configuration (which are now defaults) as well as a library when the user what extra configuration.

The overrides are applied to the config resulting after processing `Cargo.toml`(s). I don't see how accepting "a set of configuration" will help with this (not to mention this is already what it does). I think we can remedy this by including a command by default in `nix-cargo-integration` that one can use to query examples and attribute information. For example, one could do `help overrides.build` to get information and example about the build override. I believe that would solve your case? 

> Hmm I will set it programmatically since this didn't work and nix is way better in this regards (function to generate the sturct name, command ... etc)

Huh, it did not work? Are you sure you have the `devshell.toml` in your `root` directory (the `root` you set in `flake.nix`)?

**Comment by kkharji** [comment]
> > like nix build to build the project to /result/bin/ and nix flake check to run tests and so on.
> 
> You can still do these.

YES it does, sorry about that.

> > I think perhaps the issue, is that the template override defaults instead of supplying it. I think it would make more sense if nix-cargo-integration would act as a single function that accept an aggregated set of configuration (which are now defaults) as well as a library when the user what extra configuration.
> 
> The overrides are applied to the config resulting after processing `Cargo.toml`(s). I don't see how accepting "a set of configuration" will help with this (not to mention this is already what it does). I think we can remedy this by including a command by default in `nix-cargo-integration` that one can use to query examples and attribute information. For example, one could do `help overrides.build` to get information and example about the build override. I believe that would solve your case?

Oh I see, yah well what I was implying that everything (at least high level stuff) should be (as before, with the cool new abstractions) in the template it self, like what we had in `common.nix` file and `build.nix` file. So that the user can see everything, including comment + examples + options within the template it self without requiring external manuals or re-reads when he forgot about it.

The old template worked perfectly for me because it's give me a layout and guidelines to setup rust projects. It made extremely fast for me to start new project, modify shell env and require packages fields and get going.
 
The example and the help was the template it self, The real deference in the new change, is the complete shift from a template to a library, where the process was straightforward, READ the template and navigate your way around.

WITH TEMPLATE

- Create new project with `rust-nix-templater` 
- Edit options, follow comments, and add what you need/remove what you don't.
- Start developing.

AS A LIBRARY 

- Create new project with `rust-nix-templater` 
- Catch up and refresh your memory on `nix-cargo-integration`.  (open browser)
- Write override section and try to remember what you need to override, maybe open previous generated file to reproduce.
- Start developing and hope you wouldn't need to modify nix stuff for 
          at least few days.



> > Hmm I will set it programmatically since this didn't work and nix is way better in this regards (function to generate the sturct name, command ... etc)
> 
> Huh, it did not work? Are you sure you have the `devshell.toml` in your `root` directory (the `root` you set in `flake.nix`)?

Yes, maybe the issue because I'm still on 0.2.0, I'm having a small issue on system level right now.

**Comment by kkharji** [comment]
> Huh, it did not work? Are you sure you have the devshell.toml in your root directory (the root you set in flake.nix)?

It does work :/ only after adding it to the version control. I feel so dump :face_with_head_bandage:

**Comment by 90-008** [comment]
> Oh I see, yah well what I was implying that everything (at least high level stuff) should be (as before, with the cool new abstractions) in the template it self, like what we had in common.nix file and build.nix file. So that the user can see everything, including comment + examples + options within the template it self without requiring external manuals or re-reads when he forgot about it.

So if I understood it right, what you want is `rust-nix-templater` to "generate" default override fields for further config? These would be commented of course.

**Comment by kkharji** [comment]
@yusdacra Yah I guess this would be a easier transition. It would be cool if it isn't commented out and `nix-cargo-integration` will not override with empty lists or `""` empty strings, so not everything get commented out.

It would be also nice if there are place to have devshell config as well. 

@yusdacra :laughing: the recent changes made me feel so lost, I didn't know the new repo brought down the template down to a single line.

**Comment by 90-008** [comment]
> It would be also nice if there are place to have devshell config as well.

You can override the devshell config via `overrides.shell` eg:
```nix
# ...
let
	overrides = {
		shell = common: prev: {
			buildInputs = prev.buildInputs ++ [ common.pkgs.libxkbcommon ];
		};
	};
in inputs.lib.nixCargoIntegration.makeOutputs { root = ./.; inherit overrides; }
# ...
```

I will get to writing a full-fledged template with all overrides explained and commented soon.

**Comment by kkharji** [comment]
please tag me somehow to help out or review in a pr. I really want this to be awesome :D

**Comment by 90-008** [comment]
@tami5 I pushed https://github.com/yusdacra/rust-nix-templater/commit/5228eb0ccd1e866540119fa2b047c7795810d856, could you provide feedback on it?

**Comment by kkharji** [comment]
> @tami5 I pushed https://github.com/yusdacra/rust-nix-templater/commit/5228eb0ccd1e866540119fa2b047c7795810d856, could you provide feedback on it?

sure give me 10 mins

**Comment by kkharji** [comment]
Few questions:

- is things add in common fields will be applied in shell and build as before?
- in line 45-49 `These also get added to packages` what do you mean by that?
- How `shell.env` differ from `common.env`
- How to specify homepage and nixpkg description?

Suggestions:

- examples implementation for cargoTestOptions and cargoBuildOptions, and what's the different/use cases for override/overrideMain
- field to add/register flakes and/or overlay.

Awesome work @yusdacra THANKS SO MUCH :heart: :heart: , now It's way better then before  I like it a lot. It feels less overwhelming and user friendly.

**Comment by 90-008** [comment]
> is things add in common fields will be applied in shell and build as before?

Yes. The common attribute set is shared by both shell and build derivations. So overriding it will change those both two too.

> in line 45-49 These also get added to packages what do you mean by that?

That just means that the commands you add as a package (`{ package = pkgs.git; }` etc.) will also be added to the `packages` of the development shell.

> How shell.env differ from common.env

As their name implies, shell.env is only exported in the development shell. common.env is exported in both build derivation and development shell.

> How to specify homepage and nixpkg description?

The homepage is taken from the `package.homepage` field of `Cargo.toml`. Description is taken from `package.description`. A long description can be specified with `package.metadata.nix.longDescription`.

> field to add/register flakes and/or overlay.

You add flakes as inputs, it doesn't really have anything to do with the template. Adding overlays can be done via using the common.sources attribute while overriding common. For example:
```nix
prev: {
	pkgs = import prev.sources.nixpkgs { system = prev.system; overlays = [ inputs.someInput.overlay ]; };
}
```

**Comment by kkharji** [comment]
Thanks @yusdacra . You are so amazing, I appreciate your work a lot. closing the issue.
