### ISSUE TITLE
Run `cargo init` as last step if a project doesn't already exist

### ISSUE THREAD

**Issue by cyntheticfox** [yusdacra/rust-nix-templater#5]
Not sure how complex it would be to implement, but running `cargo init` with the package name would be super useful as a final step. If it can also init as a library when passing the `-L` flag, that'd be even better.

**Comment by 90-008** [comment]
This should be fairly easy to implement. We can check for the existence of a `Cargo.toml` before running `cargo init`. I'm not sure if `cargo init` does this, if it does we can just get away by calling `cargo init`.
