### ISSUE TITLE
Have output directory name default to project name

### ISSUE THREAD

**Issue by cyntheticfox** [yusdacra/rust-nix-templater#7]
It's pretty common when you create a Rust project with Cargo, that you name the directory the same as the project. My recommendation as such is since you take in the project name to define the built `flake.nix`, also default to naming the output directory the same as the project.

**Comment by 90-008** [comment]
How about using a naming scheme like `<project name>-nix-files` for default output path?

**Comment by cyntheticfox** [comment]
That could work, but might be unexpected. The main use cases for this project I can think of are "I have a project and I want to turn it into a flake" and so they already have a directory, and will set the output path, and "I'm starting a new project from scratch" and so they won't have a directory, and so would probably just set the name and license, thinking it would generate the project for them with the name they gave it.

**Comment by cyntheticfox** [comment]
I guess my real point of confusion is what I'm expecting. I was thinking the project would basically generate a starting repo with a flake and everything, or could be used to turn a project into a flake easily.

As it is, maybe what I think is the scope is too large for what this repo is supposed to do. In fact, that could probably even be another project in its own right that uses this one.

**Comment by 90-008** [comment]
> I guess my real point of confusion is what I'm expecting. I was thinking the project would basically generate a starting repo with a flake and everything, or could be used to turn a project into a flake easily.

We can do both easily. So what I think is, we should probably default to generating the files in the current directory. This will remove the need to set output directory, since I believe most use cases will be that. Generating a starting Rust project will be handled by #5.

**Comment by cyntheticfox** [comment]
That would work, yeah. Current directory would be a common enough scenario for a default.
